"""スキャン結果をMarkdown形式に変換するレポート生成器"""
from datetime import datetime
from typing import Any

PRODUCT_NAMES = {
    "finops": "FinOps JP — AWSコスト分析レポート",
    "cloudguard": "CloudGuard JP — AWSセキュリティスキャンレポート",
    "infrascore": "InfraScore JP — インフラ健全性スコアレポート",
    "supplyguard": "SupplyGuard JP — サプライチェーンセキュリティ評価レポート",
    "zerovis": "ZeroVis JP — ゼロトラスト成熟度評価レポート",
}

AXIS_LABELS = {
    "availability": "可用性",
    "performance": "パフォーマンス",
    "security": "セキュリティ",
    "cost_efficiency": "コスト効率",
    "identity": "ID・認証",
    "device": "デバイス管理",
    "application": "アプリケーション",
    "network": "ネットワーク",
}


def generate_markdown_report(product: str, result: dict[str, Any], created_at: datetime) -> str:
    title = PRODUCT_NAMES.get(product, f"{product} レポート")
    date_str = created_at.strftime("%Y年%m月%d日 %H:%M")

    lines = [
        f"# {title}",
        "",
        f"**生成日時**: {date_str}",
        f"**製品**: {product}",
        "",
        "---",
        "",
    ]

    generators = {
        "finops": _finops_report,
        "cloudguard": _cloudguard_report,
        "infrascore": _score_report,
        "zerovis": _score_report,
        "supplyguard": _supplyguard_report,
    }
    gen = generators.get(product)
    if gen:
        lines.extend(gen(result))
    else:
        lines.append("```json")
        import json
        lines.append(json.dumps(result, ensure_ascii=False, indent=2))
        lines.append("```")

    ai = result.get("ai_suggestions")
    if ai:
        lines += ["", "---", "", "## AI 改善提案（Claude）", "", str(ai), ""]

    lines += ["", "---", "", f"*Generated by {PRODUCT_NAMES.get(product, product)}*"]
    return "\n".join(lines)


def _finops_report(result: dict) -> list[str]:
    lines = ["## コスト概要", ""]
    summary = result.get("summary", {})
    if summary:
        lines.append(f"| 項目 | 値 |")
        lines.append(f"|------|-----|")
        lines.append(f"| 集計期間 | {summary.get('period', '-')} |")
        total = summary.get('total_cost', 0)
        lines.append(f"| 合計コスト | ${total:,.2f} |")
        lines.append("")

    services = result.get("top_services", [])
    if services:
        lines += ["## サービス別コスト", ""]
        lines.append("| サービス | コスト ($) | 割合 |")
        lines.append("|---------|-----------|------|")
        for s in services:
            lines.append(f"| {s.get('service')} | ${s.get('cost', 0):,.2f} | {s.get('pct', 0):.1f}% |")
        lines.append("")

    recs = result.get("recommendations", [])
    if recs:
        lines += ["## 削減推奨事項", ""]
        for r in recs:
            lines.append(f"- {r}")
        lines.append("")
    return lines


def _cloudguard_report(result: dict) -> list[str]:
    lines = [
        "## 検出サマリー", "",
        f"| 重大度 | 件数 |",
        f"|--------|------|",
        f"| 合計 | {result.get('total', 0)} |",
        f"| CRITICAL | {result.get('critical', 0)} |",
        f"| HIGH | {result.get('high', 0)} |",
        "",
    ]
    findings = result.get("findings", [])
    if findings:
        lines += ["## 検出事項一覧", ""]
        lines.append("| 重大度 | ルール | リソース |")
        lines.append("|--------|--------|---------|")
        for f in findings:
            lines.append(f"| {f.get('severity')} | {f.get('rule')} | {f.get('resource')} |")
        lines.append("")
    return lines


def _score_report(result: dict) -> list[str]:
    score = result.get("score", 0)
    grade = result.get("grade", "-")
    level = result.get("level", "")

    lines = [
        "## 総合スコア", "",
        f"**スコア**: {score} / 100  |  **グレード**: {grade}",
    ]
    if level:
        lines.append(f"**成熟度レベル**: {level}")
    lines.append("")

    breakdown = result.get("breakdown", {})
    if breakdown:
        lines += ["## 軸別スコア", ""]
        lines.append("| 評価軸 | スコア | 重み |")
        lines.append("|--------|--------|------|")
        for key, axis in breakdown.items():
            label = AXIS_LABELS.get(key, key)
            weight = int(axis.get("weight", 0) * 100)
            lines.append(f"| {label} | {axis.get('score', 0)} | {weight}% |")
        lines.append("")
    return lines


def _supplyguard_report(result: dict) -> list[str]:
    vendors = result.get("vendors", [])
    if not vendors:
        return ["*評価データなし*"]

    lines = [
        "## ベンダー評価サマリー", "",
        "| ベンダー名 | グレード | 総合スコア | SBOM/CVE | アンケート | インシデント |",
        "|-----------|---------|-----------|---------|----------|------------|",
    ]
    for v in vendors:
        lines.append(
            f"| {v.get('name')} | {v.get('grade')} | {v.get('score')} "
            f"| {v.get('sbom', '-')} | {v.get('questionnaire', '-')} | {v.get('incident', '-')} |"
        )
    lines.append("")
    return lines
